name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  Node_CI:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017 
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Node packages
      run: npm install
    - name: Running Tests
      run: npm test
